const ETH_BLOCK_TIME_IN_SECONDS: number = 12;
const NUM_BLOCKS_IN_EPOCH: number = 32;
const NUM_SECONDS_IN_EPOCH: number = ETH_BLOCK_TIME_IN_SECONDS * NUM_BLOCKS_IN_EPOCH;
const NUM_MINUTES_IN_EPOCH: number = NUM_SECONDS_IN_EPOCH / 60;
const NUM_EPOCHS_IN_HOUR: number = 60 / NUM_MINUTES_IN_EPOCH;
const NUM_EPOCHS_IN_DAY: number = NUM_EPOCHS_IN_HOUR * 24;

export { ETH_BLOCK_TIME_IN_SECONDS };
export { NUM_BLOCKS_IN_EPOCH };
export { NUM_SECONDS_IN_EPOCH };
export { NUM_MINUTES_IN_EPOCH };
export { NUM_EPOCHS_IN_HOUR };
export { NUM_EPOCHS_IN_DAY };