name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: crawlData Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_IP}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{secrets.SSH_USER}} # User of the server you want to ssh into
          port: ${{secrets.PORT}}
          script: |
            cd ~/production/decarbon/decarbon-demo/
            println deployedTime.txt
            npm run stop-estimator
            cd ~
            rm -rf production
            mkdir production
            git@github.com:decarbon-protocol/decarbon.git
            cd decarbon
            cd decarbon-demo
            rm -rf deployedTime.txt
            echo $(date +'%m/%d/%Y/%T' + main) > deployedTime.txt
            cat deployedTime.txt
            npm run start-estimator
            ps -aef | grep node
