name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: crawlData Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_IP}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USER }} # User of the server you want to ssh into
          port: ${{ secrets.PORT }}
          script: |
            cd ~
            killall node
            rm -rf production
            mkdir production
            cd production
            git clone git@github.com:decarbon-protocol/decarbon.git
            echo 'Clone to digital ocean finished'
            cd decarbon
            cd decarbon-demo
            // npm install
